nameOverride: ""
fullnameOverride: "db-go-chive"

serviceAccountName: "db"

image: 
  repository: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/db/go-chive
  tag: 10.1.0

livenessProbe: {}

readinessProbe: {}

resources: {}

securityContext: {}

affinity: {}

priorityClassName: db

nodeSelector:
  service: db

tolerations:
  - effect: NoSchedule
    key: DbOnly
    value: "true"
    operator: Equal