{{- if .Values.user.password.secretManager.key -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.user.secretName }}
  labels:
    {{- include "pg-job.labels" . | nindent 4 }}
    app.kubernetes.io/instance:  {{ .Values.user.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: {{ .Values.user.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .Values.user.name }}"
        password: "{{ `{{ .password }}` }}"
  data:
  {{ if .Values.user.password.secretManager.key -}}
  - secretKey: password
    remoteRef:
      key: {{ .Values.user.password.secretManager.key }}
      property: {{ .Values.user.password.secretManager.property }}
  {{- end }}
{{- end -}}
