{{- if and .Values.sa.enabled (not .Values.sa.shared) }}
{{- $labels := include "base-cronjobs.labels" . -}}
{{- $fullName := include "base-cronjobs.fullname" . -}}
{{- range .Values.cronJobs }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ replace "." "-" (lower (trunc 48 .name)) }}
  namespace: {{ $.Values.namespace }}
  labels: {{ $labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $fullName }}
    app.kubernetes.io/name: {{ .name  }}
  {{- with ( .saLabels | default $.Values.cronJobDefault.sa.labels ) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    app.example-org.io/service: {{ replace "." "-" (lower (trunc 48 .name)) }}
  {{- with ( .saAnnotations | default $.Values.cronJobDefault.sa.annotations ) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
