key:
  components:
    # - chart:
    #     name: argocd-image-updater
    #     repo: https://argoproj.github.io/argo-helm
    #     version: 0.11.2
    #     namespace: argocd
    #     values_path: argocd-image-updater/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: argo-cd
    #     repo: https://argoproj.github.io/argo-helm
    #     version: 7.7.6
    #     namespace: argocd
    #     values_path: argo-cd/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: metrics-server
    #     repo: https://kubernetes-sigs.github.io/metrics-server
    #     version: 3.11.0
    #     namespace: kube-system
    #     values_path: metrics-server/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: node-local-dns
    #     repo: https://charts.deliveryhero.io
    #     version: 1.1.5
    #     namespace: kube-system
    #     values_path: node-local-dns/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: datadog
    #     repo: https://helm.datadoghq.com
    #     version: 3.110.14
    #     namespace: datadog
    #     values_path: datadog-agent/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: k8s-cleaner
    #     repo: ghcr.io/gianlucam76/charts
    #     version: 0.13.0
    #     namespace: k8s-cleaner
    #     values_path: k8s-cleaner/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: robusta
    #     repo: https://robusta-charts.storage.googleapis.com
    #     version: 0.23.0
    #     namespace: robusta
    #     values_path: robusta/values.yaml
    #     auto_sync: true
    # - chart:
    #     name: kube-prometheus-stack
    #     repo: https://prometheus-community.github.io/helm-charts
    #     version: 66.3.0
    #     namespace: monitoring
    #     values_path: monitoring/prometheus-stack.yaml
    #     auto_sync: false
