{{- if .Values.cronJobDefault.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "base-cronjobs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.cronJobDefault.externalSecrets.extractKey }}
      decodingStrategy: {{ .Values.cronJobDefault.externalSecrets.decodingStrategy | default "None" }}
{{- end }}