# -- 서비스 이름 정의 (정의 하지 않을 경우 default 설정됨 - 설정 권장)
# @default -- `""` (default: {{ .Release.Name }})

appName: ""

env: "dev"

tolerations: []
affinity: {}
# @default -- `{}`  (If you set a value, the fixed value is removed (requires setting).
#  podAntiAffinity:
#    preferredDuringSchedulingIgnoredDuringExecution:
#      - weight: 99
#        podAffinityTerm:
#          labelSelector:
#            matchExpressions:
#            - key: "app.kubernetes.io/name"
#              operator: In
#              values:
#              - {{ include "base-helm.realname" . }}
#          topologyKey: "kubernetes.io/hostname"
nodeSelector: {}

# topologySpreadConstraints: []

# -- Deployment 정의
deployment:
  replicas: 2
  # -- deployment 추가 label 설정
  # @default -- `{}` (default: {{ base-helm.selectorLabels }})
  labels: {}
  #  app: test-app
  annotations: {}
  image:
    # -- 사용 할 컨테이너 이미지
    # @default -- `""` (default: nginx)
    repository: ""
    # -- 사용 한 컨테이너 이미지 태그
    # @default -- `""` (default: nginx:1.14.2)
    tag: ""
    # -- 이미지 pull 정책
    # @default -- `""` (default: IfNotPresent)
    # @options -- IfNotPresent, Always, Never
    imagePullPolicy: ""
  env: []
  #  - name: DB_PASSWORD
  #    value: null
  command: []
  #  - "echo"
  args: []
  #  - "test"
  securityContext: {}
  # @default --
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 3000
  port: 80
  volumes: []
  #  - name: test-vol
  #    emptyDir: {}
  volumeMounts: []
  #  - mountPath: /temp
  #    name: test-vol
  livenessProbe: {}
  #  failureThreshold: 3
  #  httpGet:
  #    path: /health-check
  #    port: http
  #  initialDelaySeconds: 10
  #  periodSeconds: 10
  #  successThreshold: 1
  #  timeoutSeconds: 1
  readinessProbe: {}
  #  failureThreshold: 3
  #  httpGet:
  #    path: /health-check
  #    port: http
  #  initialDelaySeconds: 10
  #  periodSeconds: 10
  #  successThreshold: 1
  #  timeoutSeconds: 1
  startupProbe: {}
  #  failureThreshold: 3
  #  httpGet:
  #    path: /health-check
  #    port: http
  #  initialDelaySeconds: 10
  #  periodSeconds: 10
  #  successThreshold: 1
  #  timeoutSeconds: 1
  resources: {}
  #  requests:
  #    memory: "64Mi" (default: 1024Mi)
  #    cpu: "250m" (default: 250m)
  #  limits:
  #    memory: "128Mi" (default: 1024Mi)
  #    cpu: "500m" (default: 2000m)
  # @default -- `""` (default: 4)
  revisionHistoryLimit: ""
  # @default -- `""` (default: 25%)
  maxSurge: ""
  # @default -- `""` (default: 0)
  maxUnavailable: ""
  terminationGracePeriodSeconds: 90
  priorityClassName: ""

rollout:
  enabled: false
  blue_green:
    enabled: false
    options: {}
    #  https://argoproj.github.io/argo-rollouts/features/bluegreen/
    #  autoPromotionEnabled: false
  canary:
    enabled: false
    options: {}
    #  https://argoproj.github.io/argo-rollouts/features/canary/

additionalPorts:
  # - targetPort: 8002
  #   servicePort: 8002
  #   portName: metric

ingress:
  # - name: test-app
  #   annotations:
  #   rules:
  #     - host: test-app.beta.iexample-org.com
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #           serviceName: test
  #           portName: http

service:
  type: ClusterIP
  port: 80
  portName: ""
  annotations: {}
  # - service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

externalSecrets:
  enabled: false
  extractKey: ""
  decodingStrategy: ""
  env: []
  #  - key: db_password
  #    alias: prefix_db_password
  #  - key: slack_token

secrets:
  enabled: false
  annotations: {}
  #  kubernetes.io/service-account.name: "test-sa"
  data: {}
  #  "API_KEY": dev
  #  "DB_PASSWORD": common

configmap:
  enabled: false
  data: {}
  #  app.name: "test-app"
  #  app.url: "https://test-app.beta.iexample-org.com"
  #  app.propertiers: |
  #    env=prod
  #    check=/health-check

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage:
  annotations: {}
sa:
  enabled: false
  shared: false
  # name: "name of sevice account"
  annotations: {}
  #  eks.amazonaws.com/role-arn: arn:aws:iam::517727162249:role/test-app-eks-iam-role

securityGroups:
  enabled: false
  groupIds: []
  # - sg-0101010101010101

pdb:
  enabled: false
  # @default -- `""` (default: 1)
  maxUnavailable: 1

datadog:
  enabled: true
  profile:
    enabled: false
  # type: "js"
  # libVersion: "v4.22.0"

global:
  deployment:
    labels: {}
    annotations: {}

  ingress:
    # - name: test-global-app
    #   annotations:
    #   rules:
    #     - host: test-global-app.beta.iexample-org.com
    #       paths:
    #         - path: /
    #           pathType: Prefix
    #           serviceName: test
    #           portName: http

  sa:
    enabled: false
    annotations: {}
    #  eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/test-app-eks-iam-role

  securityGroups:
    groupIds: []
    # - sg-0101010101010101

  hpa:
    enabled: false
    minReplicas:
    maxReplicas:
    targetCPUUtilizationPercentage:
    annotations: {}

  datadog:
    enabled: true
    profile:
      enabled: false
    # type: "js"
    # libVersion: "v4.22.0"
