name: 개발 배포

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: demo-dev-ecr_demo-cron-python

jobs:
  build-arm64:
    name: Build ARM64
    runs-on: LinuxARM64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Info for image tag
        id: image_info
        run: |
          echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(cat .project-version)" >> $GITHUB_OUTPUT
          echo "environment=dev" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ARM64 image
        run: |
          docker buildx build \
            --push \
            --build-arg CACHEBUST=${{ github.run_number }} \
            --build-arg ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY_DEV }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg GIT_PERSONAL_ACCESS_TOKEN=${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }} \
            --build-arg IMAGE_TAG=${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            --build-arg DD_GIT_REPOSITORY_URL=$(git config --get remote.origin.url) \
            --build-arg DD_GIT_COMMIT_SHA=$(git rev-parse HEAD) \
            --cache-from type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:arm64-cache \
            --cache-to type=registry,mode=max,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:arm64-cache,image-manifest=true,oci-mediatypes=true \
            --platform linux/arm64 \
            --attest type=provenance,disabled=true \
            --file .dockerfile/Dockerfile.dev \
            --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:arm64-${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            .

  build-amd64:
    name: Build AMD64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Info for image tag
        id: image_info
        run: |
          echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(cat .project-version)" >> $GITHUB_OUTPUT
          echo "environment=dev" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push AMD64 image
        run: |
          docker buildx build \
            --push \
            --build-arg CACHEBUST=${{ github.run_number }} \
            --build-arg ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY_DEV }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg GIT_PERSONAL_ACCESS_TOKEN=${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }} \
            --build-arg IMAGE_TAG=${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            --build-arg DD_GIT_REPOSITORY_URL=$(git config --get remote.origin.url) \
            --build-arg DD_GIT_COMMIT_SHA=$(git rev-parse HEAD) \
            --cache-from type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:amd64-cache \
            --cache-to type=registry,mode=max,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:amd64-cache,image-manifest=true,oci-mediatypes=true \
            --platform linux/amd64 \
            --attest type=provenance,disabled=true \
            --file .dockerfile/Dockerfile.dev \
            --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:amd64-${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            .

  merge:
    name: Merge Docker Images
    runs-on: ubuntu-latest
    needs: [build-arm64, build-amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create Info for image tag
        id: image_info
        run: |
          echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(cat .project-version)" >> $GITHUB_OUTPUT
          echo "environment=dev" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Merge and push multi-arch image
        run: |
          docker buildx imagetools create \
            --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:arm64-${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:amd64-${{ github.run_number }}-${{ steps.image_info.outputs.version }}-${{ steps.image_info.outputs.environment }}-${{ steps.image_info.outputs.sha_short }}
