---
org: ""
categorie: ""
env: ""
vpc_endpoints:
  enabled: false

datadog_private_link:
  enabled: false

vpc_peering:
  enabled: false
  connections: []

secondary_level_domain: "iexample-org.com"
github_org: "https://github.com/wetripod"
cloudfront:
  origin_access_controls: "sign requests"
ecr:
  - "demo-back"
  - "demo-alwalk-back"
  - "demo-seller-back"
  - "demo-admin-back"
  - "demo-shorts-back"
  - "alfarm-back"
  - "demo-games-back"
  - "demo-square-back"
  - "demo-shorts-reco-back"
  - "demo-reco-back"
  - "demo-drama-back"
  - "demo-altoon-back"
  - "demo-almart-back"
  - "demo-garden-back"
  - "demo-pollcom-back"
  - "demo-cron"
  - "demo-cron-pay"
  - "demo-cron-python"
  - "demo-assignment-front"
  - "demo-config"
  - "demo-ml-business-back"
  - "demo-algarden-back"
  - "db-dbm"
  - "demo-node-scraper"
  - "demo-search-back"
  - "demo-front-code-push-console"
  - "demo-strategy-back"
  - "abwayz"
  - "demo-lowest-crawler-realtime"

frontend:
  [
    "demo-shop-front",
    "demo-altto-front",
    "demo-brainteaser-front",
    "demo-storybook",
    "demo-admin-front",
    "demo-ads-front",
    "demo-price-front",
    "demo-altoon-web-front",
    "demo-alfarm-v2-front",
    "shopin-front",
    "shopin-partners-front",
    "price-csx-front",
    "demo-events-front",
    "demo-grocery-assitant-front",
  ]

loki:
  enabled: false
