---
org: "example-org"
category: "security"
env: "prod"

# CloudTrail Configuration
cloudtrail:
  enabled: true
  trail_name: "management-events"
  s3_bucket_name: "aws-cloudtrail-logs-123456789012-6667d3cb"

gitops:
  workspace_repo_url: "https://github.com/wetripod/demo-gitops-manifest"
