{{- if .Values.secret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: demo-prod-db-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: example-org_admin
      remoteRef:
        key: {{ .Values.secret.secretKey }}
        property: example-org_admin
{{- end -}}