{{- range .Values.statefulSets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  labels:
    app: {{ .name }}
type: Opaque
{{- if .secret }}
  {{- if .secret.data }}
data:
  {{- range $key, $value := .secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- else }}
  {{- end }}
{{- else }}
{{- end }}
{{- end }}