{{- if and .Values.sa.enabled (not .Values.sa.shared) }}
{{- $labels := include "base-scraper.labels" . -}}
{{- $fullName := include "base-scraper.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ replace "." "-" (lower (trunc 48 .name)) }}
  namespace: {{ $.Values.namespace }}
  labels: {{ $labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $fullName }}
    app.kubernetes.io/name: {{ .name  }}
  annotations:
    {{- include "base-helm.sa.annotations" . | nindent 4 }}
---
{{- end }}
