{{- range .Values.statefulSets }}
{{- if and .configMap (hasKey .configMap "data") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  labels:
    app: {{ .name }}
data:
  {{- range $key, $value := .configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
{{- end }}
{{- end }}
