apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.existingSecret.name }}-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: {{ .Values.existingSecret.name }}
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key:  {{ required "secretKey is required" .Values.existingSecret.secretKey }}
      property: username
  - secretKey: password
    remoteRef:
      key:  {{ required "secretKey is required" .Values.existingSecret.secretKey }}
      property: password
