{{- if .Values.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-helm.realname" . }}
  labels:
    {{- include "base-helm.labels" . | nindent 4 }}
data:
  {{- with .Values.configmap.data }}
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end}}