application_name: demo-cronjobs-nodejs
chart:
  name: demo-cronjobs-nodejs
  version: 0.0.20
  values: .helm/demo-cronjobs-prod-values.yaml
slack_channel: C0794BUEYAX
source: nodejs
repo:
  helm_values: https://github.com/wetripod/demo-cron
  ecr: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/demo-prod-ecr_demo-cron
