nameOverride: ""
fullnameOverride: "db-go-chive"

serviceAccountName: ""

image: 
  repository: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/db/go-chive
  tag: 1.5-go-chive

livenessProbe: {}

readinessProbe: {}

resources: {}

securityContext: {}

affinity: {}

nodeSelector: {}

priorityClassName: {}

tolerations: []