# 보일러플레이트 템플릿 - 환경별 설정 파일
# 사용법: 이 파일을 복사하여 각 환경(dev/prod/staging)에 맞게 수정

# CronJob 서비스 템플릿
application_name: demo-cronjobs-nodejs
chart:
  name: demo-cronjobs-nodejs
  version: 0.0.20
  values: .helm/demo-cronjobs-{ENV}-values.yaml  # {ENV}를 dev/prod/staging으로 변경
slack_channel: C082JSFBL7L  # dev: C082JSFBL7L, prod: C0794BUEYAX
source: nodejs
repo:
  helm_values: https://github.com/wetripod/demo-cron
  ecr: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/demo-{ENV}-ecr_demo-cron  # {ENV}를 dev/prod로 변경

---
# 일반 서비스 템플릿
application_name: demo-back
chart_name: demo-back
chart_version: 0.0.50
slack_channel: C082JSFBL7L  # dev: C082JSFBL7L, prod: C0794BUEYAX
type: active
source: nodejs
source_repo: https://github.com/wetripod/demo-back

---
# Scraper 서비스 템플릿
application_name: demo-node-scraper
chart_name: demo-node-scraper
chart_version: 0.0.20
slack_channel: C082JSFBL7L  # dev: C082JSFBL7L, prod: C0794BUEYAX
type: active
source: nodejs
source_repo: https://github.com/wetripod/demo-scraper