apiVersion: v2
name: base-scraper
description: A Helm chart for Kubernetes
icon: https://always-bucket-dev.s3.us-west-1.amazonaws.com/AlwayZ+로고파일.png
type: application
version: 0.0.27
appVersion: 0.0.27
