{{- if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-helm.realname" . }}
  labels:
    {{- include "base-helm.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end}}