{{- if and .Values.sa.enabled (not .Values.sa.shared) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-helm.realname" . }}
  labels:
    {{- include "base-helm.labels" . | nindent 4 }}
  annotations:
    {{- include "base-helm.sa.annotations" . | nindent 4 }}
{{- end }}