{{- if .Values.user }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mongodb-exporter.fullname" . }}
  labels:
    {{- include "prometheus-mongodb-exporter.labels" . | nindent 4 }}
stringData:
  username: {{ required "user.namme is required" .Values.user.name }}
  password: {{ required "user.password is required" .Values.user.password }}
{{- end -}}

