{{- if .Values.secretManager }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prometheus-mongodb-exporter.fullname" . }}
  labels:
    {{- include "prometheus-mongodb-exporter.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    {{- if .Values.secretManager.secretName }}
    name: {{ .Values.secretManager.secretName }}
    {{- else }}
    name: {{ include "prometheus-mongodb-exporter.fullname" . }}
    {{- end }} 
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key:  {{ required "secretKey is required" .Values.secretManager.secretKey }}
      property: username
  - secretKey: password
    remoteRef:
      key:  {{ required "secretKey is required" .Values.secretManager.secretKey }}
      property: password
{{- end -}}